# Utilizar una imagen oficial de Python como base
FROM python:3.8-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Crea el directorio /contenido dentro del contenedor
RUN mkdir /contenido

# Copiar la aplicación escribe al directoro de trabajo
COPY escribe.py .

# Ejecutar nuestra aplicación al lanzar el contenedor
CMD ["python", "./escribe.py"]